In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("dmel-all-r6.31.gtf", sep='\t', header=None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8
0,X,FlyBase,gene,19961297,19969323,.,+,.,"gene_id ""FBgn0031081""; gene_symbol ""Nep3"";"
1,X,FlyBase,mRNA,19961689,19968479,.,+,.,"gene_id ""FBgn0031081""; gene_symbol ""Nep3""; tra..."
2,X,FlyBase,5UTR,19961689,19961845,.,+,.,"gene_id ""FBgn0031081""; gene_symbol ""Nep3""; tra..."
3,X,FlyBase,exon,19961689,19961845,.,+,.,"gene_id ""FBgn0031081""; gene_symbol ""Nep3""; tra..."
4,X,FlyBase,exon,19963955,19964071,.,+,.,"gene_id ""FBgn0031081""; gene_symbol ""Nep3""; tra..."

In [4]:
df.columns=['seqname','source','feature','start','end','Xscore','strand','Xframe','attributes']

In [5]:
df[['gene id','1','2','3','4','5']]= df.attributes.str.split(";",expand=True,)

In [6]:
df.drop(df[df.feature != 'gene'].index, inplace=True)

In [7]:
df['iso1']=df['end']-df['start']

In [8]:
df= df.drop(['start','seqname','source','attributes','feature','strand','end','Xscore','Xframe','1','2','3','4','5'], axis=1)

In [10]:
df= df.sort_values(by=['iso1'])

In [11]:
df.head()

                      gene id  iso1
307664  gene_id "FBgn0085765"    29
435196  gene_id "FBgn0267503"    29
435242  gene_id "FBgn0267518"    29
435260  gene_id "FBgn0267524"    29
435175  gene_id "FBgn0267496"    29

In [12]:
#df.to_csv('copy_number.csv', index=False)

# This is where the first "script" would be made, and stop. Once the ref csv was started, the below script would be run with all the files in the working directory

In [ ]:
import pandas as pd
import numpy as np

In [25]:
df= pd.read_csv("copy_number.csv")

In [26]:
df.head()

                       0  length
0  gene_id "FBgn0085765"      29
1  gene_id "FBgn0267518"      29
2  gene_id "FBgn0267524"      29
3  gene_id "FBgn0267510"      29
4  gene_id "FBgn0267503"      29

In [38]:
df1= pd.read_csv("B59_liftoff", sep='\t', header=None)

In [39]:
df1.columns=['seqname','source','feature','start','end','Xscore','strand','Xframe','attributes']

In [15]:
df1.drop(df1[df1.feature != 'gene'].index, inplace=True)

In [43]:
df1[['gene id','1','2','3','4','5','6','7','8']]= df1.attributes.str.split(";",expand=True,)

In [17]:
df1['sample 2']=df1['end']-df1['start']

In [18]:
df1= df1.drop(['start','seqname','source','attributes','feature','strand','end','Xscore','Xframe','1','2','3','4','5','6','7','8'], axis=1)

In [19]:
df1= df1.sort_values(by=['sample 2'])

In [44]:
df1.head()

,seqname,source,feature,start,end,Xscore,strand,Xframe,attributes,gene id,1,2,3,4,5,6,7,8
0,Chr-2L,Liftoff,gene,89123,91075,.,+,.,"gene_id ""FBgn0031208""; gene_symbol ""CR11023""; ...","gene_id ""FBgn0031208""","gene_symbol ""CR11023""","coverage ""0.998""","sequence_ID ""0.996""","extra_copy_number ""0""","copy_num_ID ""FBgn0031208_0""",,None,None
1,Chr-2L,Liftoff,exon,89123,89709,.,+,.,"gene_id ""FBgn0031208""; gene_symbol ""CR11023""; ...","gene_id ""FBgn0031208""","gene_symbol ""CR11023""","transcript_id ""FBtr0475186""","transcript_symbol ""CR11023-RE""","Parent ""FBgn0031208""","extra_copy_number ""0""",,None,None
2,Chr-2L,Liftoff,exon,89786,91075,.,+,.,"gene_id ""FBgn0031208""; gene_symbol ""CR11023""; ...","gene_id ""FBgn0031208""","gene_symbol ""CR11023""","transcript_id ""FBtr0475186""","transcript_symbol ""CR11023-RE""","Parent ""FBgn0031208""","extra_copy_number ""0""",,None,None
3,Chr-2L,Liftoff,pseudogene,89123,91075,.,+,.,"gene_id ""FBgn0031208""; gene_symbol ""CR11023""; ...","gene_id ""FBgn0031208""","gene_symbol ""CR11023""","transcript_id ""FBtr0475186""","transcript_symbol ""CR11023-RE""","Parent ""FBgn0031208""","extra_copy_number ""0""",,None,None
4,Chr-2L,Liftoff,gene,91430,102955,.,-,.,"gene_id ""FBgn0002121""; gene_symbol ""l(2)gl""; c...","gene_id ""FBgn0002121""","gene_symbol ""l(2)gl""","coverage ""0.996""","sequence_ID ""0.993""","extra_copy_number ""0""","copy_num_ID ""FBgn0002121_0""",,None,None

In [23]:
df2 = pd.merge(df, df1, how="outer", on="gene id")

In [24]:
print(df2)

                     gene id     iso1  sample 2
0      gene_id "FBgn0085765"       29       NaN
1      gene_id "FBgn0267503"       29       NaN
2      gene_id "FBgn0267518"       29       NaN
3      gene_id "FBgn0267524"       29       NaN
4      gene_id "FBgn0267496"       29       NaN
...                      ...      ...       ...
17841  gene_id "FBgn0028369"   394148  375378.0
17842  gene_id "FBgn0263780"   396035       NaN
17843  gene_id "FBgn0267429"   434040       NaN
17844  gene_id "FBgn0267430"   709420       NaN
17845  gene_id "FBgn0267431"  1965856       NaN

[17846 rows x 3 columns]

In [30]:
unmapped=df2[df2['gene id'] == 'NaN']

In [32]:
unmapped.head()

Empty DataFrame
Columns: [gene id, iso1, sample 2]
Index: []

In [63]:
unmapped= df1[~df1['4'].str.contains('0')]

In [64]:
unmapped=df1[~df1['5'].str.contains('0')]

In [65]:
unmapped

,seqname,source,feature,start,end,Xscore,strand,Xframe,attributes,gene id,1,2,3,4,5,6,7,8
43577,Chr-2L,Liftoff,exon,8625110,8625182,.,+,.,"gene_id ""FBgn0051895""; gene_symbol ""tRNA:Phe-G...","gene_id ""FBgn0051895""","gene_symbol ""tRNA:Phe-GAA-1-3""","transcript_id ""FBtr0079692""","transcript_symbol ""tRNA:Phe-GAA-1-3-RA""","Parent ""FBgn0051895""","extra_copy_number ""1""",,None,None
43578,Chr-2L,Liftoff,tRNA,8625110,8625182,.,+,.,"gene_id ""FBgn0051895""; gene_symbol ""tRNA:Phe-G...","gene_id ""FBgn0051895""","gene_symbol ""tRNA:Phe-GAA-1-3""","transcript_id ""FBtr0079692""","transcript_symbol ""tRNA:Phe-GAA-1-3-RA""","Parent ""FBgn0051895""","extra_copy_number ""1""",,None,None
74412,Chr-2L,Liftoff,exon,16834138,16834265,.,-,.,"gene_id ""FBgn0261068""; gene_symbol ""LSm7""; tra...","gene_id ""FBgn0261068""","gene_symbol ""LSm7""","transcript_id ""FBtr0343770""","transcript_symbol ""LSm7-RC""","Parent ""FBgn0261068""","extra_copy_number ""1""",,None,None
74413,Chr-2L,Liftoff,exon,16834160,16834809,.,-,.,"gene_id ""FBgn0261068""; gene_symbol ""LSm7""; tra...","gene_id ""FBgn0261068""","gene_symbol ""LSm7""","transcript_id ""FBtr0080934""","transcript_symbol ""LSm7-RA""","Parent ""FBgn0261068""","extra_copy_number ""1""",,None,None
74414,Chr-2L,Liftoff,exon,16834399,16834809,.,-,.,"gene_id ""FBgn0261068""; gene_symbol ""LSm7""; tra...","gene_id ""FBgn0261068""","gene_symbol ""LSm7""","transcript_id ""FBtr0308804""","transcript_symbol ""LSm7-RB""","Parent ""FBgn0261068""","extra_copy_number ""1""",,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198612,Chr-2R,Liftoff,miRNA,20861389,20861410,.,+,.,"gene_id ""FBgn0263546""; gene_symbol ""mir-4985"";...","gene_id ""FBgn0263546""","gene_symbol ""mir-4985""","transcript_id ""FBtr0309661""","transcript_symbol ""mir-4985-RA""","Parent ""FBgn0263546""","extra_copy_number ""1""",,None,None
198613,Chr-2R,Liftoff,miRNA,20861425,20861446,.,+,.,"gene_id ""FBgn0263546""; gene_symbol ""mir-4985"";...","gene_id ""FBgn0263546""","gene_symbol ""mir-4985""","transcript_id ""FBtr0309662""","transcript_symbol ""mir-4985-RB""","Parent ""FBgn0263546""","extra_copy_number ""1""",,None,None
198614,Chr-2R,Liftoff,pre_miRNA,20861361,20861461,.,+,.,"gene_id ""FBgn0263546""; gene_symbol ""mir-4985"";...","gene_id ""FBgn0263546""","gene_symbol ""mir-4985""","transcript_id ""FBtr0309660""","transcript_symbol ""mir-4985-RM""","Parent ""FBgn0263546""","extra_copy_number ""1""",,None,None
524118,Chr-X,Liftoff,exon,19488673,19489401,.,-,.,"gene_id ""FBgn0265705""; gene_symbol ""asRNA:CR44...","gene_id ""FBgn0265705""","gene_symbol ""asRNA:CR44512""","transcript_id ""FBtr0340613""","transcript_symbol ""asRNA:CR44512-RA""","Parent ""FBgn0265705""","extra_copy_number ""1""",,None,None
524119,Chr-X,Liftoff,ncRNA,19488673,19489401,.,-,.,"gene_id ""FBgn0265705""; gene_symbol ""asRNA:CR44...","gene_id ""FBgn0265705""","gene_symbol ""asRNA:CR44512""","transcript_id ""FBtr0340613""","transcript_symbol ""asRNA:CR44512-RA""","Parent ""FBgn0265705""","extra_copy_number ""1""",,None,None